### ISSUE TITLE
Username Relation

### ISSUE THREAD

**Issue by HummingBird24** [chloedeguzman/Kollab#11]
Need a way to insert/edit based off of username not databaseID.
For example, after the user signs up, we want to be able to insert his or her profession, interest, and profile pic in relation to his or her username.

**Comment by thackson** [comment]
You are already able to insert a user without the id. 
I added an edit function in the index.js that allows you to edit the bio table. The bio table is the one that has the profession, interest, and profile pic attributes. In order to edit the bio you just need to put in the username.
