### ISSUE TITLE
Array like input for interest and profession.

### ISSUE THREAD

**Issue by HummingBird24** [chloedeguzman/Kollab#12]
![screen shot 2017-10-14 at 12 06 41 pm](https://user-images.githubusercontent.com/16395981/31578545-483a6b7c-b0d8-11e7-9e7b-39140d70a519.png)
Want to be able to insert multiple interest and professions to the database. Attached is a screetshot of a ugly version of how a user would get started after signup and the things they would select.

**Comment by thackson** [comment]
Ok I made this change. the new version is 1.14
